
GET http://localhost:8000/api/v1/abc

###
GET http://localhost:8000/api/v1/dishes
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzI4MjQxOSwiZXhwIjoxNzIzMjg2MDE5fQ.LydDvl209m9aCZLCo9CquSGCY42F_rdsUmMB0a0c32Y
###
POST http://localhost:8000/api/v1/employees/create
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzM2MDQ1OCwiZXhwIjoxNzIzMzY0MDU4fQ.MZvddcN9ot8d-HF3qK7tECVAu5O3KhKLAc08_R-iVnE

{
    "name": "Lê Văn Cương",
    "username": "nhanvien1",
    "password": "Nhanvien123",
    "phone": "34546756775",
    "role": "employee",
    "position": "Nhân viên phục vụ",
    "hire_date": "2004-04-26"
}

###
POST http://localhost:8000/api/v1/employees/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "Admin123"
}

###
GET http://localhost:8000/api/v1/employees/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzM2MDQ1OCwiZXhwIjoxNzIzMzY0MDU4fQ.MZvddcN9ot8d-HF3qK7tECVAu5O3KhKLAc08_R-iVnE

