
GET http://localhost:8000/api/v1/abc

###
GET http://localhost:8000/api/v1/employees/infor
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJhZG1pbjEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjM5MTQzNzcsImV4cCI6MTcyMzkxNDQzN30.XRGi5fy17WUjW3-7MMD-a3VpVE07HUdaG3NgRRP470U
###
POST http://localhost:8000/api/v1/employees/create
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzM2MDQ1OCwiZXhwIjoxNzIzMzY0MDU4fQ.MZvddcN9ot8d-HF3qK7tECVAu5O3KhKLAc08_R-iVnE

{
    "name": "Lê Văn Cương",
    "username": "nhanvien1",
    "password": "Nhanvien123",
    "phone": "34546756775",
    "role": "employee",
    "position": "Nhân viên phục vụ",
    "hire_date": "2004-04-26"
}

###
POST http://localhost:8000/api/v1/employees/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "Admin123"
}

###
PATCH http://localhost:8000/api/v1/employees/change-password
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJhZG1pbjEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjM5MTY4NDQsImV4cCI6MTcyMzkyMDQ0NH0.jcrqCMeliuUZ0uNXkRbZkLI2mshNO6EustWNi9KIfp4
Content-Type: application/json

{
    "oldPassword": "Admin1234",
    "newPassword": "Admin123"
}

###
GET http://localhost:8000/api/v1/employees/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMzM2MDQ1OCwiZXhwIjoxNzIzMzY0MDU4fQ.MZvddcN9ot8d-HF3qK7tECVAu5O3KhKLAc08_R-iVnE

